### ISSUE TITLE
Repository language incorrectly classified

### ISSUE THREAD

**Issue by wbuchanan** [wdxtub/Patriots#1]
It looks like this should probably be getting tagged as a Python or JavaScript repository, but is currently getting classified as a Stata repository.  You can set configuration parameters to correct the language mapping without a ton of effort and it would make your repository visible to audiences that might be more inclined to contribute.

**Comment by wdxtub** [comment]
Thanks for the kindly reminder! I've update the .gitattributes file to identify the project language~
